In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from sklearn import datasets

---

When we are working with variable length sequences, we might need to select a specific slice from a sequence. We can use flattened tensors and gather operations to get select the output at a specific timestep

In [3]:
sess = tf.InteractiveSession()

In [75]:
batch_size = 5
time_steps = 3
k = 4

In [76]:
X = tf.placeholder(tf.float32, [batch_size, time_steps, k])
X_output_size = int(k)
X_batch_size = X.get_shape()[0]
X_flattened = tf.reshape(X, [-1, k])
selection_indices = tf.placeholder(tf.int32, [None,])
flattened_selection_indices = tf.range(0, batch_size) * time_steps + selection_indices

In [77]:
selection = tf.gather(X_flattened, flattened_selection_indices, axis=0)

In [78]:
X

<tf.Tensor 'Placeholder_21:0' shape=(5, 3, 4) dtype=float32>

In [79]:
X_flattened

<tf.Tensor 'Reshape_8:0' shape=(15, 4) dtype=float32>

In [80]:
selection

<tf.Tensor 'Gather_2:0' shape=(5, 4) dtype=float32>

In [81]:
A = np.random.rand(batch_size, time_steps, k).astype(np.float32)
A

array([[[ 0.79958975,  0.04464632,  0.08849371,  0.87835395],
        [ 0.80319917,  0.24316388,  0.15327922,  0.18373381],
        [ 0.7893191 ,  0.05568036,  0.26829067,  0.59789759]],

       [[ 0.8512516 ,  0.12393252,  0.45251042,  0.62429982],
        [ 0.44793329,  0.36718974,  0.75134903,  0.25594243],
        [ 0.59193766,  0.21244124,  0.42044288,  0.79898679]],

       [[ 0.87896442,  0.39654842,  0.5050087 ,  0.6789363 ],
        [ 0.16767943,  0.78050047,  0.81229246,  0.04635869],
        [ 0.0377044 ,  0.37618402,  0.43867671,  0.26192546]],

       [[ 0.06118996,  0.88865322,  0.97053295,  0.44828236],
        [ 0.64886379,  0.77903336,  0.00388553,  0.4894155 ],
        [ 0.10664324,  0.25346676,  0.83599156,  0.95961893]],

       [[ 0.79824281,  0.75885653,  0.02351428,  0.29025006],
        [ 0.90880919,  0.99687147,  0.30702126,  0.52609718],
        [ 0.43593967,  0.96661997,  0.80834734,  0.74272126]]], dtype=float32)

In [82]:
B = np.array([0, 0, 2, 1, 0], dtype=np.int32)

In [83]:
C = sess.run(selection, feed_dict={X: A, selection_indices: B})
print(C.shape)
print(C)

(5, 4)
[[ 0.79958975  0.04464632  0.08849371  0.87835395]
 [ 0.8512516   0.12393252  0.45251042  0.62429982]
 [ 0.0377044   0.37618402  0.43867671  0.26192546]
 [ 0.64886379  0.77903336  0.00388553  0.4894155 ]
 [ 0.79824281  0.75885653  0.02351428  0.29025006]]
